### ISSUE TITLE
FR: Consider making footer_text user-definable

### ISSUE THREAD

**Issue by mrand** [dylandoamaral/uptime-card#1]
This card is a great way to display more history in a compact way! I suspect when people see this card, they will be interested in this for displaying data other than "uptime" - could be any sort of history.  In fact, your very first example is such a thing: you are showing a "New Update" available, which of course, isn't "uptime" :-)

As such, it would be nice if the text below the bars was user-definable: 

https://github.com/dylandoamaral/uptime-card/blob/a5e3773a9385a4184ff1a41419cba00606877314/src/uptime-card.ts#L439

Perhaps by introducing these two config var's:

### Global configuration

| Name | Type | Default | Since | Description |
|------|:----:|:-------:|:-----:|-------------|
| footer_text | string |  | v0.0.2 | Set a custom label to the card.  Defaults to "% uptime"

If `footer_text` is present but empty, it wouldn't show any text or even a % sign.

### Show configuration

| Name | Type | Default | Since | Description |
|------|:----:|:-------:|:-----:|-------------|
| average | boolean | true | v0.0.2 | Show the computed average.

This would allow for not having a number there when it isn't wanted, while still keeping the footer_text.

### Footer discussion

Having said all that, I found it ever so slightly confusing that the footer line is showing two unrelated things: the date range labels, and the computed average - yet they are connected together with a line.  I'm not sure removing the line would really fix it though.  I appreciate that the whole thing is compact, but I wonder about moving the computed average and footer_text up to the left of the icon.  This could allow for displaying the those things while not displaying date range labels.  Just a random idea to consider.

**Comment by mrand** [comment]
> This issue will only add `average` and maybe `average_text` instead of `footer_text` since the information may not be in the footer for the future release.

Indeed.  I was just using footer to maintain consistency with current for the sake of discussion.  Makes no sense to call it that if it's separated, and `average_text` makes a lot of sense to me.

Related to this FR, I'll just point out that "uptime-card" might be a misleading name... it can do so much more than uptime! :-)

**Comment by dylandoamaral** [comment]
That's true it is more a metaphorical term since every binary element is `up` sometime and `down` for the rest of the time. And also I am very bad at naming xD.

**Comment by mrand** [comment]
I'm not saying you need to change the name, but if you're looking for other ideas, you could solicit on your Reddit thread.  

Averaging-bar-card is the first thing that came to mind - and that would work even if you or someone else ever expands it to allowing for averaging numerical sensors rather than just binary.

**Comment by dylandoamaral** [comment]
It is very interesting don't hesitate to create other issues since you have so many ideas. I will include them in future release!
