### ISSUE TITLE
Safari and Chrome handling title_template differently

### ISSUE THREAD

**Issue by ntompson** [dylandoamaral/uptime-card#104]
Following the upgrade to v0.8.1, I've discovered that Safari and Chrome are handling the new `title_template` field differently:

- In Safari, the title is rendered from `title_template`
- In Chrome, the title is rendered from `name`

I've configured both fields to the same thing so that I get consistent results in both browsers (I tend to use Chrome on the desktop, while the iOS HA app uses Safari). But I'm assuming this is not the intended behaviour!

**Comment by dylandoamaral** [comment]
I think this is due to the cache of your web explorer. Clear it and try again!

**Comment by ntompson** [comment]
My humble apologies - you're absolutely right! Should have tried that first...

Thanks for your quick reply. All is well.
