### ISSUE TITLE
switch domain support

### ISSUE THREAD

**Issue by sshalyminov** [dylandoamaral/uptime-card#116]
Can you please add switch domain support? For now it shows nothing (just gray), like unavailable.

**Comment by dylandoamaral** [comment]
You want me to suppport switch entities ?

**Comment by sshalyminov** [comment]
Yes, to show the switching history as well as for binary_sensor. The switch can be "on" or "off" and this can be used for your card. And probably input_boolean - it has the same behavior. 
Of course I can create template binary_sensor to reflect switch or input_boolean just for your card but why to breed extra entities?

**Comment by dylandoamaral** [comment]
You also can configure your card to match your need without creating any new sensor.

But I will add it to uptime-card I think it is a good idea 👍🏻

**Comment by sshalyminov** [comment]
Thank you!
