### ISSUE TITLE
Option to define values that are considered as OK

### ISSUE THREAD

**Issue by Jeetah** [dylandoamaral/uptime-card#123]
I have an uptime card based on a sensor that has values: on, off, unknown
I can map: 
OK: on
KO: off
But "unknown" is considered as KO. So it makes sense to offer another option to define values, that should be additionally considered as OK/KO. Or if easier: An option to consider all other values as OK or KO.

**Comment by dylandoamaral** [comment]
I advice you to lookt at https://github.com/dylandoamaral/uptime-card#ok-and-ko-options. It should works either you specify the ko or the ok parameter.
