### ISSUE TITLE
Value for OK and KO

### ISSUE THREAD

**Issue by vellanix** [dylandoamaral/uptime-card#124]
I have a sensor that return two value: true and false.
I need to assign the 'true' to ok, and 'false' to ko, but I'm not able to do that.
I suppose that I cannot use true and false in the code...

There's any trick to use them? Maybe using "" ?

Thank you

**Comment by dylandoamaral** [comment]
I just tried and it works using "", but why you didn't try that solution before opening this issue ?

**Comment by vellanix** [comment]
Sorry,

i tried before writing but i was wrong because i tried "true" instead of "True" with the capital letter...
Sorry again
