### ISSUE TITLE
uptime kuma

### ISSUE THREAD

**Issue by warlordattack** [dylandoamaral/uptime-card#133]
hello how to link uptime kuma to this card please ?

the HACS integration for uptime kuma is impossible to add into HACS 
so impossible to get sensors from uptime kuma
https://github.com/meichthys/uptime_kuma
(archived repo, impossible to add to hacs)

is there an other way to link uptime kuma to this card please ?

**Comment by dylandoamaral** [comment]
I don't know, my card only "show" the data created by other library such as https://github.com/meichthys/uptime_kuma. I don't know what is Kuma I can't help you with it.

**Comment by warlordattack** [comment]
finally the repo owner un-archived it ant this solved my problem :)
