### ISSUE TITLE
Support for entities: instead of entity:

### ISSUE THREAD

**Issue by alexdelprete** [dylandoamaral/uptime-card#136]
Love your card, really. You made a great job. :)

The only issue is that when monitoring MANY similar sensors, the code becomes difficult to maintain. It could be easily solved with the plugin [auto-entities](https://community.home-assistant.io/t/auto-entities-automatically-fill-cards-with-entities/147801), but that needs the card to support `entities:` vs `entity:`.

Could you please implement this? It would really help in many use-cases.

Thank you.

**Comment by dylandoamaral** [comment]
I don't have time today, I will check this as soon as possible !

**Comment by alexdelprete** [comment]
@dylandoamaral did you have a chance to take a look at this?

**Comment by dylandoamaral** [comment]
I wanted to do this tonight but it is more difficult than expected. If I understand what you are looking for, you want the card to repeat an uptime card for each entity you put inside the entities field right ?

**Comment by alexdelprete** [comment]
Yes. Something like auto-entities: https://github.com/thomasloven/lovelace-auto-entities.

Auto-entities has a lot of functionalities obviously, I just think that having an uptime card configuration, and wanting to repeat it for multiple sensors would be enough.

I hope it's not too difficult, and I much appreciate your willingness to implement this, I think other users will appreciate it too. :)

**Comment by dylandoamaral** [comment]
Personally I use https://github.com/custom-cards/decluttering-card for that use case. But I can understand that auto entities have several cool features such as filtering. However, I am sad that autoentities can't take a card with only one entity and repeat it itself...

**Comment by alexdelprete** [comment]
Yes I know the decluttering-card, but auto entities has a more _direct_ and _elegant_ approach, but that is entirely subjective obviously. Filtering and other features are really useful.

Anyway, for your uptime-card, all I thought was missing was to have the possibility to support a list of entities vs only one. Don't really need all the features of auto entities. A simple list would be more than enough.

**Comment by dylandoamaral** [comment]
Honestly I tried to implement it but it doesn't work well with the card. It broke a lot of thing such as aliases for example. I won't implement it as if, I don't think it is a good idea. The best solution would be a card that convert any entity card into an entities card repeating it for each entity.

**Comment by dougmaitelli** [comment]
Wish this was re-considered, I have 20+ uptime monitors from uptime-kuma and would love to use auto-entities to generate a list of uptime cards automatically, right now this is not possible and I have to manually add a card on the dashboard for every entity.

**Comment by dougmaitelli** [comment]
Ok, answering this, I achieved what the original thread wanted:
```
  - type: "custom:auto-entities"
    card:
      type: custom:vertical-stack-in-card
      card_mod:
      style:
        div uptime-card:
          $: |
            ha-card.flex {
              padding-top: 5px;
              padding-bottom: 3px;
            }
    card_param: cards
    filter:
      include:
        - integration: uptime_kuma
          attributes:
            device_class: connectivity
          options:
            type: custom:uptime-card
            bar:
              height: 15
            show:
              icon: false
              status: false
              footer: false
    sort:
      method: name
    show_empty: false
```

**Comment by alexdelprete** [comment]
> Ok, answering this, I achieved what the original thread wanted:

Doug, thank you so much. I don't know how you did it, but when I tried last year, I was missing the `entities:` so I opened the issue. I didn't try after that...

Cheers.
