### ISSUE TITLE
Additional padding on footer

### ISSUE THREAD

**Issue by pqpxo** [dylandoamaral/uptime-card#14]
Unsure if its simply my setup but using the example configurations result in extra padding on the footer ...

ha-card > div {
    padding: 0px 16px 16px;
}

![image](https://user-images.githubusercontent.com/43624115/112740342-c1c33300-8f6b-11eb-874a-b1157904b4aa.png)

**Comment by dylandoamaral** [comment]
Hmmm, do you have any custom theme? Normally it should not happen thanks to this style from `style.ts`:
```css
ha-card > div:last-child {
    padding-bottom: 0;
}
```
I will still make a PR to try to make the card less dependent to themes.
