### ISSUE TITLE
this.config.ko.map is not a function

### ISSUE THREAD

**Issue by apedance** [dylandoamaral/uptime-card#141]
Hello!

Not sure if this is really related to the uptime-card itself - but I only get it with this card.
Sorry is this is not caused by this custom card.

Any help is appreciated.

![image](https://user-images.githubusercontent.com/4264240/200196790-ba1c2e44-3803-4228-af22-fab4593799a8.png)

**Comment by dylandoamaral** [comment]
false is a reserved keyword, try with `"false"`

**Comment by dylandoamaral** [comment]
Seems to be solved, feel free to open the issue if it still not working.
