### ISSUE TITLE
Footer time range not in language of home assistant

### ISSUE THREAD

**Issue by h3llrais3r** [dylandoamaral/uptime-card#148]
Hi, love your card, but I would like to be able to get the footer time range in my language. 
Now it's always in English:
![image](https://user-images.githubusercontent.com/1945295/212568733-0d9cce27-263f-4065-9bf1-9ca8ada6c4cc.png)

Can this be translated? Or maybe also be templated so I can put my own language?

**Comment by Z0mbiel0ne** [comment]
Hey @h3llrais3r if your really want to change the text in the footer, use the following workaround:

1. Go inside `/config/www/community/uptime-card/uptime-card.js` and edit the following lines:
https://github.com/dylandoamaral/uptime-card/blob/254e1645b2b197b3c6b6f1f77993cb7f57b7213c/src/uptime-card.ts#L735
https://github.com/dylandoamaral/uptime-card/blob/254e1645b2b197b3c6b6f1f77993cb7f57b7213c/src/uptime-card.ts#L757
https://github.com/dylandoamaral/uptime-card/blob/254e1645b2b197b3c6b6f1f77993cb7f57b7213c/src/uptime-card.ts#L761
https://github.com/dylandoamaral/uptime-card/blob/254e1645b2b197b3c6b6f1f77993cb7f57b7213c/src/uptime-card.ts#L763
https://github.com/dylandoamaral/uptime-card/blob/254e1645b2b197b3c6b6f1f77993cb7f57b7213c/src/uptime-card.ts#L767
https://github.com/dylandoamaral/uptime-card/blob/254e1645b2b197b3c6b6f1f77993cb7f57b7213c/src/uptime-card.ts#L769
https://github.com/dylandoamaral/uptime-card/blob/254e1645b2b197b3c6b6f1f77993cb7f57b7213c/src/uptime-card.ts#L772
https://github.com/dylandoamaral/uptime-card/blob/254e1645b2b197b3c6b6f1f77993cb7f57b7213c/src/uptime-card.ts#L774
https://github.com/dylandoamaral/uptime-card/blob/254e1645b2b197b3c6b6f1f77993cb7f57b7213c/src/uptime-card.ts#L778
https://github.com/dylandoamaral/uptime-card/blob/254e1645b2b197b3c6b6f1f77993cb7f57b7213c/src/uptime-card.ts#L780
2. Optional: If you use HACS, according to [HACS documentation](https://hacs.xyz/docs/categories/plugins/#special-notes-about-downloaded-lovelace-plugins) delete the generated `/config/www/community/uptime-card/uptime-card.gz`
3. Delete your Cache
4. ???
5. PROFIT!!!
<img width="376" alt="image" src="https://user-images.githubusercontent.com/16578286/223417302-1fe8d21a-8580-47c8-ac94-24311688f912.png"><img width="373" alt="image" src="https://user-images.githubusercontent.com/16578286/223418163-cb188d9b-1384-4cd1-a201-06f8355670ab.png"><img width="373" alt="image" src="https://user-images.githubusercontent.com/16578286/223419015-264f2566-fa9f-4e05-b875-ca74d3011658.png"><img width="373" alt="image" src="https://user-images.githubusercontent.com/16578286/223419683-38af080d-994b-465a-a0df-792ceb75bc44.png">

But don't forget that after an update of uptime-card
your changes will be overwritten by HACS.

**Comment by h3llrais3r** [comment]
Thanks for the info, but don't want to touch source code for now, so I'll live with the fact that it's in English by default.
