### ISSUE TITLE
Uptime average is not showing when value is 0

### ISSUE THREAD

**Issue by h3llrais3r** [dylandoamaral/uptime-card#149]
When the uptime is 0, the average template is never rendered.

![image](https://user-images.githubusercontent.com/1945295/215849868-ee78287e-f37b-4ae7-ac7e-ecbff02594bc.png)

```
average_template: >-
  [[[
  let date = new Date(0);
  seconds = Math.trunc((configuration.hours_to_show * 3600) * variables.uptime / 100);
  date.setSeconds(seconds);
  return date.toISOString().substr(11, 8) + ' (' + variables.uptime.toFixed(2) + '%)';
  ]]]
```

Code indicates that it's only rendered when value > 0:
![image](https://user-images.githubusercontent.com/1945295/215850905-0306d82d-aedc-4b05-bc90-bec7d4710ce6.png)

**Comment by dylandoamaral** [comment]
Thanks it will be available for the next release.
