### ISSUE TITLE
Add 'ko_icon' in 'color' config

### ISSUE THREAD

**Issue by KKnishev** [dylandoamaral/uptime-card#150]
Is it possible to add a new tag 'ko_icon:' in 'color:' config?
```
color:
  icon: white
  ko_icon: grey
```

**Comment by dylandoamaral** [comment]
`icon_adaptive_color` is not enough for your use case ?

**Comment by KKnishev** [comment]
not really, the idea was to "turn off" the icon in off status, but `icon_adaptive_color` use entity colors
