### ISSUE TITLE
not working in home assistant 2023.3.1

### ISSUE THREAD

**Issue by MrAredhone** [dylandoamaral/uptime-card#152]
hey all I updated to HA 2023.3.1 
and now I get the error Custom element Doesn't exist: uptime-card
it did work before the update I just had set it up like I wanted 
I'm also really new to HA and still tumbling around 
so do I need to wait for a update
or do I need something else 
I really love this card but I had to remove it because the error moved everything else
of the screen 

thanks in advanced Aredhone

**Comment by dylandoamaral** [comment]
Normally the card is still compatible, did you use HACS to install your cards ?

**Comment by MrAredhone** [comment]
yes i did install it with HACS

**Comment by dylandoamaral** [comment]
Did you try to uninstall the card and install it again ?

**Comment by MrAredhone** [comment]
i  did not and will right now

**Comment by MrAredhone** [comment]
o it worked thanks allot now i know that for the future
