### ISSUE TITLE
[BUG] Uncaught (in promise) errors in browser

### ISSUE THREAD

**Issue by bifbaf** [dylandoamaral/uptime-card#156]
Hi I getting lots of errors in my browser using this integration.

See the following screenshot

![image](https://github.com/dylandoamaral/uptime-card/assets/99833578/984909b3-054f-468a-8eaf-72426be72a30)

Is this because of a wrong configuration or is this a bug?

**Comment by dylandoamaral** [comment]
Do you still have this issue ?

**Comment by bifbaf** [comment]
No, I think it was fixed during an update. This error is gone. I will close this issue.
Thanks
