### ISSUE TITLE
Duration doesn't work

### ISSUE THREAD

**Issue by Soulfly999** [dylandoamaral/uptime-card#176]
Hey, i tried several settings, but the duration doesn't work. It shows only 24 hours

So see my code above:

type: custom:uptime-card
entity: binary_sensor.diskstation_120j
icon: 'mdi:server'
status_adaptive_color: true
title_adaptive_color: false
tooltip_adaptive_color: true
icon_adaptive_color: true
duration:
  quantity: 1
  unit: year

![2024-04-23 08_22_29-Übersicht – Home Assistant – Mozilla Firefox](https://github.com/dylandoamaral/uptime-card/assets/4936794/60abab46-78d8-4484-ad51-e6b98db2c938)

With the old settings **hours_to_show** it works?
![2024-04-23 08_29_14-Übersicht – Home Assistant – Mozilla Firefox](https://github.com/dylandoamaral/uptime-card/assets/4936794/dd56bfb5-e19e-4bb8-aa5d-17553c59d3a2)

**Comment by dylandoamaral** [comment]
Are you sure you have the correct card version ? Can you check in the console inspector the printed version please ?

**Comment by Soulfly999** [comment]
Ok, it seems to be an update problem. I deleted it via hacs and installed it again and now it works
