### ISSUE TITLE
Add support for HACS 2.0

### ISSUE THREAD

**Issue by HunterX86** [dylandoamaral/uptime-card#178]
Today i wanted to install the uptime-card via hacs, but got this error:
> The version for this integration can not be used with HACS.

Can you make changes in the integration so that it supports HACS 2.0

**Comment by matthewmorris09** [comment]
Any updates on this? I'm looking to start using this if I can but this issue makes it seem like it's no longer compatible?

**Comment by dylandoamaral** [comment]
No, I rapidly check what the migration steps to take, but didn't find anything.

**Comment by dylandoamaral** [comment]
I think I should follow https://www.hacs.xyz/docs/publish/, will try to check this week if I have time.

**Comment by dylandoamaral** [comment]
More precisely https://www.hacs.xyz/docs/publish/plugin/#requirements.

**Comment by dylandoamaral** [comment]
I don't know why, everything seem correct. If anybody know why HACS don't accept the card, write a message !

**Comment by HunterX86** [comment]
I got it installed. I don't know how, but it works.
