### ISSUE TITLE
Theme w/ Rounded Corners cuts off card

### ISSUE THREAD

**Issue by Blueion76** [dylandoamaral/uptime-card#184]
I'm having an issue where whenever I apply the Material Rounded HACS theme, uptime card gets cut off. I think i've narrowed it down to something with the rounded corner implementation, not 100% sure though. See attached.
![brave_13Da1BnUJW](https://github.com/user-attachments/assets/afa26d72-42fe-4e8c-ba74-3d0108820f59)

**Comment by dylandoamaral** [comment]
This is not a bug of uptime card, this theme apparently is rounding the border, so ou have to add padding to the card using for example https://github.com/thomasloven/lovelace-card-mod.

**Comment by Blueion76** [comment]
> This is not a bug of uptime card, this theme apparently is rounding the border, so ou have to add padding to the card using for example https://github.com/thomasloven/lovelace-card-mod.

I have added padding and nothing changes. I'm almost positive it's something with this card because no other cards I use have this issue.

**Comment by dylandoamaral** [comment]
I think you don't add padding to the correct element.
