### ISSUE TITLE
FR: Sensor Attributes

### ISSUE THREAD

**Issue by LoneWolf345** [dylandoamaral/uptime-card#2]
Feature Request
I would like to be able to select an attribute of a sensor to monitor.  For example, the Certificate Expiry integration produces a sensor with a timestamp but also has an attribute for "is_valid" which is binary.

**Comment by dylandoamaral** [comment]
Not very confident about the result, can you tell me if everything is working using this version of the card: https://gist.github.com/dylandoamaral/1427187d1942b8fc2306755c8a324b8d ?

**Comment by LoneWolf345** [comment]
It doesn't look like it works but I could be doing something wrong.  I'm not very experienced with this.  I'll lay out what I did in case I've done it wrong.  

I'm using the cert expiry integration to monitor `home-assistant.io`.  You should be able to easily reproduce what I'm doing.

![2021-03-26 08_23_27-Fargo Office](https://user-images.githubusercontent.com/687297/112639133-edc8a200-8e0d-11eb-99ad-2a2e243655f1.png)

I replaced your new version with the existing in the `/config/www/community/uptime-card/uptime-card.js`
Rebooted HA
I added the `attribute: is_valid` to the card yaml.

Here is the full card yaml
![2021-03-26 08_35_50-Fargo Office](https://user-images.githubusercontent.com/687297/112639503-57e14700-8e0e-11eb-9b51-48522243f39a.png)

**Comment by dylandoamaral** [comment]
Normally your configuration is ok. I will try by myself using your integration ;)

**Comment by dylandoamaral** [comment]
It should work now, tested on my stack. If you can still check with your stack 🙏🏻 https://gist.github.com/dylandoamaral/b16c029ced5cca1eb80d792ee41d3e09.

**Comment by dylandoamaral** [comment]
If it is the case, I think you can still use a `template sensor` (https://www.home-assistant.io/integrations/template/) to create a sensor from the attribute.
