### ISSUE TITLE
FR : Tooltip on each bars

### ISSUE THREAD

**Issue by Gunth** [dylandoamaral/uptime-card#20]
Hi there,

First thanks for the great work of this card.

Maybe one thing that could be great would be to have a tooltip on each bars to have at least the time range of this bar and may be other values that could be useful ( or could be defined via the editor ) like in the reddit status page.

Thanks

**Comment by dylandoamaral** [comment]
Yes I planned to do that too :D. I just don't know if it will be a toolbar or inside the card next to the state (a bit like mini-graph-card).
