### ISSUE TITLE
Card doesn't render if entity has no recent state history

### ISSUE THREAD

**Issue by HITChris** [dylandoamaral/uptime-card#22]
I noticed if the entity has no recorded history, the card does not render at all, and I get various console errors:

![b](https://user-images.githubusercontent.com/34664460/112878144-32ae3c00-908d-11eb-9da6-e298cfbf638a.PNG)

As soon as I update the entity's state (e.g., from Online to Offline & back to Online):

![a](https://user-images.githubusercontent.com/34664460/112878139-30e47880-908d-11eb-96a3-6e4c30d24cba.PNG)

![image](https://user-images.githubusercontent.com/34664460/112878030-15796d80-908d-11eb-9eee-cc6775ff58fc.png)

The card then renders without issue:

![image](https://user-images.githubusercontent.com/34664460/112878091-25914d00-908d-11eb-9440-36e11f590513.png)

Excluding of course the 'map' console errors I mentioned in #13 -

![image](https://user-images.githubusercontent.com/34664460/112878718-e1527c80-908d-11eb-8e86-8f915bae3bce.png)

This particular entity's not showing _any_ recorded history does seem odd to me, even though its state has not changed in the last 24 hours. Still, might be best to default in some sort of blank/unavailable state.

```          - type: 'custom:uptime-card'
            entity: sensor.zwave_system
            icon: 'mdi:raspberry-pi'
            ok: Online
            alias:
              ok: Fully Online
            bar:
              height: 23
              round: 1
              spacing: 3
              amount: 24
            name: ZWave
            hours_to_show: 24
            icon_adaptive_color: true
            status_adaptive_color: true
            average_text: '% uptime'
```

```
recorder:
  db_url: !secret db_url
  purge_keep_days: 1
```

**Comment by dylandoamaral** [comment]
For both your issues, I have hard time reproducing the errors. I fixed two things that was problematic: #23 and #15. I don't know if it will fix your errors or not but we will try. I will make a release soon.

**Comment by HITChris** [comment]
I'm no longer seeing the console errors, which makes sense per #15. However with v3 I'm seeing a new behavior that I was definitely not seeing with v2:

![s2](https://user-images.githubusercontent.com/34664460/112900369-030d2d00-90a9-11eb-86c8-bf8c652ac3fe.gif)

This is following a clear cache + refresh of lovelace. No console errors, just a continuous refreshing of the uptime cards....

**Comment by dylandoamaral** [comment]
Ahah yes I opened an issue #25. I didn't have that in my test environment maybe because everything is in localhost :/. It will be easy to reproduce and fix at least ! Thanks for your help !

**Comment by HITChris** [comment]
Thanks for the quick support, nice work
