### ISSUE TITLE
Bug: Blink Card

### ISSUE THREAD

**Issue by dylandoamaral** [dylandoamaral/uptime-card#25]
Since the version 0.0.3 the card seems to blink. I think this is due to #23. I should try to get data from cache instead of setting a default hass value...

In general I should try to handle asynchronous stuff correctly, handling together the `hass`, `setConfig` and `updateData` process.

**Comment by dylandoamaral** [comment]
Need to be fixed as fast as possible.

**Comment by Drynael** [comment]
This is what it looks like:
![flicker](https://user-images.githubusercontent.com/15029013/112941975-b4ef3c80-912f-11eb-8f5a-3e07ae6c5628.gif)
