### ISSUE TITLE
FR: template based status

### ISSUE THREAD

**Issue by ntompson** [dylandoamaral/uptime-card#28]
Absolutely love what you've done with this card: it's gold! 

One request I'd really appreciate is the ability to set custom status text based on jinja templates (or similar). I have a range of `binary_sensors` keeping track of service status; I use custom attributes to provide more detail on the status of the service. So it would be nice to be able to do something like:

```yaml
  status: '{{ state_attr('binary_sensor.solar_system', 'detail') }}'
```

Examples of how I use these currently (with a boring entities card and `custom:secondaryinfo-entity-row` to extract the `detail` attribute):

<img width="422" alt="Screen Shot 2021-03-31 at 10 26 31 am" src="https://user-images.githubusercontent.com/32885870/113069211-91012900-920b-11eb-907d-742c0f7960ea.png">

I'd much prefer to be able to use your card instead!

Nick

**Comment by dylandoamaral** [comment]
Yes this is a nice idea, but I have no idea how to use jinja template with my card. I will see if I can create my own template based status. Did you think that only attributes will be used ?

**Comment by ntompson** [comment]
Too good - you're awesome! Looking forward to having a try.

**Comment by dylandoamaral** [comment]
Ahah you're welcome hope it will work correctly. I will publish the version 0.1.0 tonight.
