### ISSUE TITLE
Does not works in android application

### ISSUE THREAD

**Issue by vodoc** [dylandoamaral/uptime-card#29]
In the android application I can not see "rainbow" bars with different colors. I see all columns with same last color.

**Comment by dylandoamaral** [comment]
Hello, I need a bit more information about your issue to fix it.

What is your YAML configuration ?
Did you try without using android ?
What is the "last color" ?
What did you mean by "rainbow bars" ?

**Comment by vodoc** [comment]
YAML:
    
    type: 'custom:uptime-card'
    entity: binary_sensor.updater
    icon: 'mdi:raspberry-pi'
    severity: 100
    ok: 'on'
    ko: 'off'
    bar:
      height: 46
      round: 1
      spacing: 4
      amount: 36
    name: Оновлення HA
    alias:
      ok: Треба оновитися!
      ko: ' '
    color:
      ok: '#C66445'
      ko: '#46C669'
    hours_to_show: 168
    show:
      footer: false
      header: true
      icon: true
      status: true
      timeline: true
      average: false
    status_adaptive_color: false
    title_adaptive_color: false
    icon_adaptive_color: false
    
It works fine in browser
![image](https://user-images.githubusercontent.com/14331936/113176893-a13df600-9255-11eb-95be-f374deb932f3.png)
In the android application it looks wrong
![image](https://user-images.githubusercontent.com/14331936/113177087-d4808500-9255-11eb-9d8f-f1f6502f5c5b.png)

**Comment by dylandoamaral** [comment]
Sadly I don't have android phone so I can't reproduce the behavior. Are you sure, that it is still green even when you changethe state of `binary_sensor.updater` to off using the developer tool UI ? It should turn yellow.

**Comment by dylandoamaral** [comment]
Because it maybe just means that you have an update since 168 hours

**Comment by vodoc** [comment]
yes. it switched to yellow after changed it in dev tools. on both UI: browser and android application. looks like it works fine. but this strange white bars at the begin.....
ok, I will monitor it.
Thank you.

**Comment by dylandoamaral** [comment]
The white bars are when the data was unknown
