### ISSUE TITLE
Hover doesn't seem to be functional in Safari

### ISSUE THREAD

**Issue by agneevX** [dylandoamaral/uptime-card#36]
## Bug Report

I don't seem to be able to hover/click on the points in Safari 14.0.3. 

https://user-images.githubusercontent.com/19761269/113513515-c7320600-9587-11eb-98b3-d5befb33dc46.mov

**Comment by dylandoamaral** [comment]
I think this is due to the cache, go to the console to verify the card version.

**Comment by agneevX** [comment]
Yep, logged in this morning and it worked as intended.
