### ISSUE TITLE
FR: Support fire-dom-event

### ISSUE THREAD

**Issue by EliotHertenstein** [dylandoamaral/uptime-card#50]
I use browser-mod to control almost every part of my Lovelace interface, and currently, I'm not able to use fire-dom-event as a "tap-action". Please add support for this, as all my more information popups are custom, and I would love to use those with this great-looking card.

Thanks!

**Comment by dylandoamaral** [comment]
What do you mean by fire-dom-event? It seems to be a script, do you mean running a script using the button ? Such as `call-service` from https://github.com/custom-cards/button-card#action ?

**Comment by EliotHertenstein** [comment]
https://github.com/thomasloven/hass-browser_mod/releases/tag/1.3.0

**Comment by EliotHertenstein** [comment]
It's a tap-action. It allows you to control browser-mod events, which is how popups are created.

**Comment by dylandoamaral** [comment]
Ok I see, I will add this one and call service for the next version.

**Comment by EliotHertenstein** [comment]
Thanks!

**Comment by EliotHertenstein** [comment]
Thanks for adding this integration! Unfortunately, when I try to use action: fire-dom-event, the clicked element of the card goes away. It physically won't let me click it. Any ideas what could be causing this?

**Comment by dylandoamaral** [comment]
Arghhh I am sorry, I will try to fix it as fast as possible.

**Comment by dylandoamaral** [comment]
Ok I tried in my stack, I never used the mod before but I think I succeed to fire a dom event. You already can do that, it is just a bug that will not show the cursor in `pointer` mode.

Here is my configuration:
```yaml
tap_action:
  action: fire-dom-event
  browser_mod:
    deviceId: a8dc43a7-f98c5572
    command: toast
    message: 'Hello, world!'
```

Can you validate that? By the way, since this version you have to click on the header to launch the tap action.

**Comment by EliotHertenstein** [comment]
Let me try it out today. Thanks again for the exceptional support here, it's really incredible :)
