### ISSUE TITLE
Specify color thresholds

### ISSUE THREAD

**Issue by agneevX** [dylandoamaral/uptime-card#53]
Can you please add support for specifying custom thresholds, that overwrite the default set levels? Thanks!

**Comment by dylandoamaral** [comment]
It is the role of the severity option. You want something more accurate that determine Ok/None/Ko independantly?

**Comment by agneevX** [comment]
With that option, I'm able to define up to three colors only.

E.g. if `uptime` is between 98% and 100%, color X... between 96% to 98% color, color Y... below 96%, color Z.

With `mini-graph-card`, that would translate to:

https://github.com/agneevX/my-ha-setup/blob/ab45835c4c5d8ba38fba71a9f71fde7c8395446d/lovelace_raw.yaml#L963-L969

**Comment by agneevX** [comment]
Dang! Almost made it to a release 😅
