### ISSUE TITLE
Glance blink to uptime card

### ISSUE THREAD

**Issue by LRvdLinden** [dylandoamaral/uptime-card#57]
Hi, is it possible to put a glance to uptime card? A red blink when it is down ![image](https://user-images.githubusercontent.com/77990847/115139915-ea06f480-a034-11eb-89f3-3f65bd54e2ca.gif)

**Comment by LRvdLinden** [comment]
So when it seems offline than the card blink. See: https://www.home-assistant.io/lovelace/glance/

**Comment by LRvdLinden** [comment]
'''yaml

style: |
                state-badge{
                  {% if is_state('sensor.ombo_online', 'Offline') %}
                    filter:  brightness(50%) grayscale(100%);
                  {% endif %}
                }
'''

**Comment by dylandoamaral** [comment]
Thanks for the example, it will help me a lot

**Comment by LRvdLinden** [comment]
![image](https://user-images.githubusercontent.com/77990847/115141326-e1fe8300-a03b-11eb-86a9-920cdf54f178.jpeg)

**Comment by LRvdLinden** [comment]
see card code: https://pastebin.com/wfPjCCde

**Comment by LRvdLinden** [comment]
![Apr-18-2021 11-54-47](https://user-images.githubusercontent.com/77990847/115141497-f55e1e00-a03c-11eb-8bf1-bb62c6707fa0.gif)
