### ISSUE TITLE
Don't appear on Iphone 6

### ISSUE THREAD

**Issue by hebbister** [dylandoamaral/uptime-card#62]
Hi, if I turn on true to show status, the uptime-card appear on PC, but not visible on Iphone HA app or chrome browser too.
[uptime-card.zip](https://github.com/dylandoamaral/uptime-card/files/6334060/uptime-card.zip)

**Comment by dylandoamaral** [comment]
Hi I think this is due to the cache. Wait and I think the card will appear.

**Comment by hebbister** [comment]
I do a Reset frontend cache action, but no change, the problem persists.

**Comment by dylandoamaral** [comment]
I am sorry, I don't have iphone 6 to try it myself, I will let it open but I have no idea how to fix that, I have personally an iphone X and it works well :/.

**Comment by agneevX** [comment]
@hebbister Can you share your card config?

**Comment by hebbister** [comment]
Here is,

    type: 'custom:uptime-card'
    entity: switch.medenceszures
    ok: 'on'
    ko: 'off'
    hours_to_show: 10
    bar:
      amount: 60
      spacing: 2
      round: 4
      height: 25
    color:
      tooltip: white
      title: light-grey
    show:
      header: true
      title: true
      icon: true
      status: true
      timeline: true
      footer: true
      average: true
    tooltip:
      hour24: true
      animation: true
    alias:
      ok: szűrés
      ko: nincs szűrés
    alignment:
      header: spaced
      icon_first: false
      status: spaced
      tooltip_first: false
    tap_action:
      action: more-info
    title_adaptive_color: false
    severity: 100
    icon_adaptive_color: false
    name: Medence szűrés ideje
    status_adaptive_color: false
    tooltip_adaptive_color: false

but, I attached it in the first comment.

**Comment by dylandoamaral** [comment]
Hey @hebbister you still have this issue ?

**Comment by hebbister** [comment]
@dylandoamaral yes, the problem has not disappeared.

**Comment by dylandoamaral** [comment]
Did you try with another version of the card ?

**Comment by hebbister** [comment]
Only with the newest version.

**Comment by hebbister** [comment]
OK, I tried with v0.3.0, but same problem.

**Comment by agneevX** [comment]
Which version of iOS are you running?

**Comment by hebbister** [comment]
iOS 12.5.2,  HA app is 2021.4.1 (2021.115), and yes I can reproduce it in Safari and Chrome browser too.

**Comment by dylandoamaral** [comment]
It is not due to the screen size since I still se my card in an emulated iphone 6 screen:
![image](https://user-images.githubusercontent.com/37652599/115852795-c1ae3a00-a428-11eb-88d0-f1ca375d77d5.png)

And sadly you can't access easily to the console logs :/

**Comment by hebbister** [comment]
Okay, I think I need to use it without a status indicator, or I have to drop my phone out and buy a new one :)

**Comment by agneevX** [comment]
> It is not due to the screen size since I still se my card in an emulated iphone 6 screen

> iOS 12.5.2

It's due to the ancient version of iOS that lacks a lot of new web technologies. iOS 12 is also EOL'd IIRC.
