### ISSUE TITLE
Footer uptime percentage seems to be wrong?

### ISSUE THREAD

**Issue by agneevX** [dylandoamaral/uptime-card#72]
Math isn't my strongest suit but when so many blips are below 98%, surely the total uptime % is less than 99.5%?

https://user-images.githubusercontent.com/19761269/115958281-724d3400-a524-11eb-9ccb-b48a341b8d40.mov

**Comment by dylandoamaral** [comment]
It seems right, according to your video we have something like this: 
`(97.77 + 97.75 + 99.96 + 98.98 + 98.87 + 98.86 + 100 + 98.87 + 97.77 + 98.89 + 100 * 5 + 98.89 + 100 + 98.88 + 100 + 100 + 98.88 + 100 * 15) / 36` and it equals to `99.56` (I certainly made several mistakes).

**Comment by agneevX** [comment]
I’m closing this for now, as I simply don’t have the mental capacity to deal with this right now... COVID :(

**Comment by dylandoamaral** [comment]
Take care !

**Comment by agneevX** [comment]
Thank you 🙏 😊
