### ISSUE TITLE
Customize the footer format

### ISSUE THREAD

**Issue by agneevX** [dylandoamaral/uptime-card#79]
Right now, the footer follows the following format:

```text
<hours_to_show> hour/s ago <line> <average_template> <line> Now
```

Would be nice if this could be specified.

**Comment by agneevX** [comment]
Also, if `hours_to_show` is less than `1`, it shows that... e.g. with value `0.5`, it shows `0.5 hours ago`.

Do you think `30 mins. ago` would be more apt?

**Comment by dylandoamaral** [comment]
For the first one, I would like, the card to be highly customizable and I am thinking of a grid based card managable by the user, however it will be for the version 1.0.0.

For the second one it is a good idea, it is already the case for hours/days/weeks I can do the same for minutes !
