### ISSUE TITLE
FR: Multiple Rows or calendar view

### ISSUE THREAD

**Issue by LoneWolf345** [dylandoamaral/uptime-card#8]
I dove all in with the uptime-card and love the look and feel of it.  I should probably list these as two different feature request but they are similar in nature.

Easy Mode) Multiple rows.  If I want to be able to see the past 4 weeks with each block representing 1 day I currently would have 28 skinny lines.  I would like to be able to specify `rows: 4` and `amount: 28` and have it render 4 rows of 7. 
![2021-03-26 08_50_44-reddit Status - Uptime History](https://user-images.githubusercontent.com/687297/112641453-6af51680-8e10-11eb-86a6-515db488ddd9.png)

Hard Mode) Calendar view.  I would like to see a copy of [https://www.redditstatus.com/uptime/](url)
![2021-03-26 08_48_16-reddit Status - Uptime History](https://user-images.githubusercontent.com/687297/112641126-12257e00-8e10-11eb-8aeb-b837d178244a.png)
Bonus Points) Include the day of the month in the colored block.

**Comment by dylandoamaral** [comment]
This one is a bit tricky however it is a nice idea. Maybe having a `mode` option setup to `calendar`. I will try to see if it can be done in a nicely way.

**Comment by dylandoamaral** [comment]
I think this would be another type of card, adding this feature is maybe too much.
