### ISSUE TITLE
Actual Value not Average

### ISSUE THREAD

**Issue by eximo84** [dylandoamaral/uptime-card#85]
Is it possible to show the actual value of the entity rather than an average?

I'm using this to show battery level. If it moves from 40% to 100% it should show green but doesn't because of the it average.

**Comment by eximo84** [comment]
Hey, thanks for getting back to me.

I have switched to the custom bar card for now but i prefer the look of the pips.  Basically rather than an average showing i just want the actual value displayed.

Example if i can explain:

Point 1: 100% = Green
Point 2: 100% = Green
Point 3: 50% = Yellow
Point 4: 25% = Red
Point 5: 75% = Yellow
Point 6: 100% = Green

Rather than an average between points determining the colour.

**Comment by dylandoamaral** [comment]
I am sorry, but I don't think it will work well with this card. If the last bar should print the actual value what the other bars should print ? It is too specific.

Maybe I didn't understand your needs, don't hesitate to reopen the issue if this is the case.
