### ISSUE TITLE
Time format always 12h AM/PM

### ISSUE THREAD

**Issue by aquaticus** [dylandoamaral/uptime-card#89]
Time range aways displayed using 12h am/pm format. Not possible to see 24h time.
Time string should use the format set in users preferences.
![time_format](https://user-images.githubusercontent.com/1891400/131411309-fffbd53a-3232-4abf-9096-876d9f75f224.png)

**Comment by dylandoamaral** [comment]
You can, inside your yaml configuration add:
```
tooltip:
  hour24: true
```

**Comment by aquaticus** [comment]
I was looking for time format but apparently I missed this one. Thanks.

**Comment by filikun** [comment]
It seems though that this option gives you 01:00-24:59 instead of 00:00-23:59
