### ISSUE TITLE
Uptime-card Not loaded in hacs

### ISSUE THREAD

**Issue by bschatzow** [dylandoamaral/uptime-card#92]
Tried to install the latest version through hacs and it appears that the files were put in the correct place. config\www\community\uptime-card
I added this to my resource file:
```
- type: module  
  url: /hacsfiles/uptime-card.js
```

and get the error uptime-card not loaded in hacs.

**Comment by dylandoamaral** [comment]
The good entry is:
```
- url: /hacsfiles/uptime-card/uptime-card.js
  type: module
```
Feel free to close this issue if it works.

**Comment by bschatzow** [comment]
I was missing the directory in my config. It works now. Thanks.
